// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwapq23hAvhf_RdmN7UZVmgUOnZOtj2NU',
    appId: '1:220917733221:web:94c09c03106ade5a37b38c',
    messagingSenderId: '220917733221',
    projectId: 'calm-photon-433216-k6',
    authDomain: 'calm-photon-433216-k6.firebaseapp.com',
    storageBucket: 'calm-photon-433216-k6.firebasestorage.app',
    measurementId: 'G-ZG030PEKB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3shfWx1Xcx2jmzvQARM_95ORZnHeMGJA',
    appId: '1:220917733221:android:f2df8eb34dddd72d37b38c',
    messagingSenderId: '220917733221',
    projectId: 'calm-photon-433216-k6',
    storageBucket: 'calm-photon-433216-k6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwapq23hAvhf_RdmN7UZVmgUOnZOtj2NU',
    appId: '1:220917733221:web:3435df643a8655a837b38c',
    messagingSenderId: '220917733221',
    projectId: 'calm-photon-433216-k6',
    authDomain: 'calm-photon-433216-k6.firebaseapp.com',
    storageBucket: 'calm-photon-433216-k6.firebasestorage.app',
    measurementId: 'G-97XL4TMMK4',
  );
}
